{"8f129459ef0776a0fa46da5fc475ea3a":{"statistic":{"failed":27,"broken":16,"skipped":0,"passed":36,"unknown":0,"total":79},"items":[{"uid":"df8b6d919379b8b6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/df8b6d919379b8b6","status":"passed","time":{"start":1731476629301,"stop":1731476629611,"duration":310}},{"uid":"6f697a7877d9002c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/6f697a7877d9002c","status":"passed","time":{"start":1731475965894,"stop":1731475966135,"duration":241}},{"uid":"d64287adea52aed","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/d64287adea52aed","status":"passed","time":{"start":1731474810920,"stop":1731474811192,"duration":272}},{"uid":"785c5fdd1f44d5aa","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/785c5fdd1f44d5aa","status":"passed","time":{"start":1730875811286,"stop":1730875811499,"duration":213}},{"uid":"e3035c274e4a2b9f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/e3035c274e4a2b9f","status":"failed","statusDetails":"AssertionError: No successful 'transferADA' log found | Failed Logs: None","time":{"start":1730865940266,"stop":1730865940509,"duration":243}},{"uid":"751936495016cba7","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/751936495016cba7","status":"failed","statusDetails":"AssertionError: No successful 'transferADA' log found | Failed Logs: None","time":{"start":1730186918381,"stop":1730186918674,"duration":293}},{"uid":"2296589570935f6e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/2296589570935f6e","status":"passed","time":{"start":1730186748529,"stop":1730186748766,"duration":237}},{"uid":"a95ac438008f462a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/a95ac438008f462a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684617,"stop":1729748684617,"duration":0}},{"uid":"5dedc5a5c87cbc3f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/5dedc5a5c87cbc3f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163114,"stop":1729680163114,"duration":0}},{"uid":"8a7d74aebb656722","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/8a7d74aebb656722","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365616,"stop":1729679365616,"duration":0}},{"uid":"3bad00801b45342f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/3bad00801b45342f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197379,"stop":1729672197379,"duration":0}},{"uid":"8a8d864d008aacf0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/8a8d864d008aacf0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682382,"stop":1729667682382,"duration":0}},{"uid":"a2c1a9a4e04c83d0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/a2c1a9a4e04c83d0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664171788,"stop":1729664171788,"duration":0}},{"uid":"1d510e4f1873a6f4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/1d510e4f1873a6f4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248137,"stop":1729574248137,"duration":0}},{"uid":"b5b706add31308ed","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/b5b706add31308ed","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364423,"stop":1729508364423,"duration":0}},{"uid":"e701e3670f04283f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/e701e3670f04283f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506658720,"stop":1729506658720,"duration":0}},{"uid":"d6ea7ee420fdf689","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/d6ea7ee420fdf689","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245928882,"stop":1729245928882,"duration":0}},{"uid":"2dc3a3b7373bd034","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/2dc3a3b7373bd034","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491645,"stop":1728386491645,"duration":0}},{"uid":"4147af62307045c9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/4147af62307045c9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137543,"stop":1728380137543,"duration":0}},{"uid":"30baf3e448e28c7c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/30baf3e448e28c7c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091737,"stop":1728370091737,"duration":0}}]},"011c6a73c3f72f6a7ca823b0704e81e3":{"statistic":{"failed":33,"broken":17,"skipped":0,"passed":29,"unknown":0,"total":79},"items":[{"uid":"a8a70e3a2e958f3f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/a8a70e3a2e958f3f","status":"passed","time":{"start":1731476629612,"stop":1731476629921,"duration":309}},{"uid":"7e26cbf00bf28bac","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/7e26cbf00bf28bac","status":"passed","time":{"start":1731475966136,"stop":1731475966373,"duration":237}},{"uid":"83c23568e37b5cdc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/83c23568e37b5cdc","status":"passed","time":{"start":1731474811193,"stop":1731474811479,"duration":286}},{"uid":"149998e512dc3566","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/149998e512dc3566","status":"failed","statusDetails":"AssertionError: No successful 'create infoAction proposal' log found | Failed Logs: [{'agentId': '4cd23a48-2aeb-4656-898a-a645b7e77921', 'functionName': 'createInfoGovAction', 'status': True, 'success': False, 'timestamp': '2024-11-06T06:44:51.718000+00:00', 'message': 'KubærApi [Status 400] : ShelleyTxValidationError ShelleyBasedEraConway (ApplyTxError (ConwayGovFailure (ProposalReturnAccountDoesNotExist (RewardAccount {raNetwork = Testnet, raCredential = KeyHashObj (KeyHash {unKeyHash = \"7a7c39ae44986064b31b22845f8319693a5a4b5c2872619622f9bc4a\"})})) :| []))', 'triggerType': 'MANUAL', 'txHash': None, 'instanceIndex': 0, 'parameters': [{'name': 'anchor', 'value': {'url': 'agents.cardanoapi.io', 'dataHash': '1111111111111111111111111111111111111111111111111111111111111111'}}], 'result': 'KubærApi [Status 400] : ShelleyTxValidationError ShelleyBasedEraConway (ApplyTxError (ConwayGovFailure (ProposalReturnAccountDoesNotExist (RewardAccount {raNetwork = Testnet, raCredential = KeyHashObj (KeyHash {unKeyHash = \"7a7c39ae44986064b31b22845f8319693a5a4b5c2872619622f9bc4a\"})})) :| []))', 'internal': [{'result': {'url': 'https://metadata.cardanoapi.io/data/4896e0a9af329c077dac38c7a4ae3079d6b0dbbbfc90b42b424eb4dc90962978', 'dataHash': '4896e0a9af329c077dac38c7a4ae3079d6b0dbbbfc90b42b424eb4dc90962978'}, 'message': '', 'success': True, 'timeStamp': '2024-11-06T06:44:51.656Z', 'parameters': ['{\"@context\":{\"@language\":\"en-us\",\"CIP100\":\"https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#\",\"CIP108\":\"https://github.com/cardano-foundation/CIPs/blob/master/CIP-0108/README.md#\",\"hashAlgorithm\":\"CIP100:hashAlgorithm\",\"body\":{\"@id\":\"CIP108:body\",\"@context\":{\"references\":{\"@id\":\"CIP108:references\",\"@container\":\"@set\",\"@context\":{\"GovernanceMetadata\":\"CIP100:GovernanceMetadataReference\",\"Other\":\"CIP100:OtherReference\",\"label\":\"CIP100:reference-label\",\"uri\":\"CIP100:reference-uri\",\"referenceHash\":{\"@id\":\"CIP108:referenceHash\",\"@context\":{\"hashDigest\":\"CIP108:hashDigest\",\"hashAlgorithm\":\"CIP100:hashAlgorithm\"}}}},\"title\":\"CIP108:title\",\"abstract\":\"CIP108:abstract\",\"motivation\":\"CIP108:motivation\",\"rationale\":\"CIP108:rationale\"}},\"authors\":{\"@id\":\"CIP100:authors\",\"@container\":\"@set\",\"@context\":{\"name\":\"http://xmlns.com/foaf/0.1/name\",\"witness\":{\"@id\":\"CIP100:witness\",\"@context\":{\"witnessAlgorithm\":\"CIP100:witnessAlgorithm\",\"publicKey\":\"CIP100:publicKey\",\"signature\":\"CIP100:signature\"}}}}},\"authors\":[],\"hashAlgorithm\":\"blake2b-256\",\"body\":{\"abstract\":\"This proposal is created automatically by agent: 991e2e65-7b72-4815-a527-bbe2ff80260e#0\",\"motivation\":\"This proposal is automatically generated by autonomous-agent-testing.\",\"references\":[{\"@type\":\"Other\",\"label\":\"autonomous-agent-testing\",\"uri\":\"https://cardanoapi.github.io/autonomous-agents/archietecture_docusaurus/docs/architecture\"}],\"title\":\"Proposal By Agent 991e2e65-7b72-4815-a527-bbe2ff80260e#0\",\"rationale\":\"This proposal was created as a part of testing for autonomous-agent-testing\"}}'], 'function_name': 'saveMetadata'}]}]","time":{"start":1730875811501,"stop":1730875811743,"duration":242}},{"uid":"445ddfe23b06e062","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/445ddfe23b06e062","status":"failed","statusDetails":"AssertionError: No successful 'create infoAction proposal' log found | Failed Logs: None","time":{"start":1730865940543,"stop":1730865940771,"duration":228}},{"uid":"45ecd768ba0d44ea","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/45ecd768ba0d44ea","status":"failed","statusDetails":"AssertionError: No successful 'create infoAction proposal' log found | Failed Logs: None","time":{"start":1730186918708,"stop":1730186919030,"duration":322}},{"uid":"569d78392c9becd0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/569d78392c9becd0","status":"failed","statusDetails":"AssertionError: No successful 'create infoAction proposal' log found | Failed Logs: [{'agentId': '27bbe84b-c1b8-46ae-a9c0-ab83be52cd30', 'functionName': 'createInfoGovAction', 'status': True, 'success': False, 'timestamp': '2024-10-29T07:20:28.844000+00:00', 'message': 'KubærApi [Status 400] : Missing Balance :[(AdaAssetId,400000)]', 'triggerType': 'MANUAL', 'txHash': None, 'instanceIndex': 0, 'parameters': [{'name': 'anchor', 'value': {'url': 'agents.cardanoapi.io', 'dataHash': '1111111111111111111111111111111111111111111111111111111111111111'}}], 'result': 'KubærApi [Status 400] : Missing Balance :[(AdaAssetId,400000)]', 'internal': [{'result': {'url': 'https://metadata.cardanoapi.io/data/2129922f969072dfe2136b5e0d85008b7088f420139b6e4e1c0fd5584ff05751', 'dataHash': '2129922f969072dfe2136b5e0d85008b7088f420139b6e4e1c0fd5584ff05751'}, 'message': '', 'success': True, 'timeStamp': '2024-10-29T07:20:28.784Z', 'parameters': ['{\"@context\":{\"@language\":\"en-us\",\"CIP100\":\"https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#\",\"CIP108\":\"https://github.com/cardano-foundation/CIPs/blob/master/CIP-0108/README.md#\",\"hashAlgorithm\":\"CIP100:hashAlgorithm\",\"body\":{\"@id\":\"CIP108:body\",\"@context\":{\"references\":{\"@id\":\"CIP108:references\",\"@container\":\"@set\",\"@context\":{\"GovernanceMetadata\":\"CIP100:GovernanceMetadataReference\",\"Other\":\"CIP100:OtherReference\",\"label\":\"CIP100:reference-label\",\"uri\":\"CIP100:reference-uri\",\"referenceHash\":{\"@id\":\"CIP108:referenceHash\",\"@context\":{\"hashDigest\":\"CIP108:hashDigest\",\"hashAlgorithm\":\"CIP100:hashAlgorithm\"}}}},\"title\":\"CIP108:title\",\"abstract\":\"CIP108:abstract\",\"motivation\":\"CIP108:motivation\",\"rationale\":\"CIP108:rationale\"}},\"authors\":{\"@id\":\"CIP100:authors\",\"@container\":\"@set\",\"@context\":{\"name\":\"http://xmlns.com/foaf/0.1/name\",\"witness\":{\"@id\":\"CIP100:witness\",\"@context\":{\"witnessAlgorithm\":\"CIP100:witnessAlgorithm\",\"publicKey\":\"CIP100:publicKey\",\"signature\":\"CIP100:signature\"}}}}},\"authors\":[],\"hashAlgorithm\":\"blake2b-256\",\"body\":{\"abstract\":\"This proposal is created automatically by agent: d4dceb32-34ee-4ae2-aa23-1993a900d604#0\",\"motivation\":\"This proposal is automatically generated by autonomous-agent-testing.\",\"references\":[{\"@type\":\"Other\",\"label\":\"autonomous-agent-testing\",\"uri\":\"https://cardanoapi.github.io/autonomous-agents/archietecture_docusaurus/docs/architecture\"}],\"title\":\"Proposal By Agent d4dceb32-34ee-4ae2-aa23-1993a900d604#0\",\"rationale\":\"This proposal was created as a part of testing for autonomous-agent-testing\"}}'], 'function_name': 'saveMetadata'}]}]","time":{"start":1730186748768,"stop":1730186749111,"duration":343}},{"uid":"dba51fbd6fe97913","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/dba51fbd6fe97913","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684736,"stop":1729748684736,"duration":0}},{"uid":"3ff590e180f02031","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/3ff590e180f02031","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163224,"stop":1729680163224,"duration":0}},{"uid":"b2e5b8fcade97f2f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/b2e5b8fcade97f2f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365726,"stop":1729679365726,"duration":0}},{"uid":"66fbc48faa06d6f1","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/66fbc48faa06d6f1","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197485,"stop":1729672197485,"duration":0}},{"uid":"e8b422e4e94d1fb5","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/e8b422e4e94d1fb5","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682497,"stop":1729667682497,"duration":0}},{"uid":"d9670ffd0ac601f0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/d9670ffd0ac601f0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664171895,"stop":1729664171895,"duration":0}},{"uid":"c7c6c981e84fd7c2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/c7c6c981e84fd7c2","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248244,"stop":1729574248244,"duration":0}},{"uid":"b1b5376ea4b774cc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/b1b5376ea4b774cc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364537,"stop":1729508364537,"duration":0}},{"uid":"6b9f0df71e83a0c5","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/6b9f0df71e83a0c5","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506658825,"stop":1729506658825,"duration":0}},{"uid":"ed9405a7795d80bf","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/ed9405a7795d80bf","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245928989,"stop":1729245928989,"duration":0}},{"uid":"f916081f991d590c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/f916081f991d590c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491751,"stop":1728386491751,"duration":0}},{"uid":"86944b89ce30adde","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/86944b89ce30adde","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137649,"stop":1728380137649,"duration":0}},{"uid":"4f5bab4501b4751a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/4f5bab4501b4751a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091844,"stop":1728370091844,"duration":0}}]},"4b813c3575320ac912016173b78fbde9":{"statistic":{"failed":15,"broken":15,"skipped":0,"passed":49,"unknown":0,"total":79},"items":[{"uid":"6202b020dd5383e7","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/6202b020dd5383e7","status":"passed","time":{"start":1731476631684,"stop":1731476631684,"duration":0}},{"uid":"15c63765b5df607f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/15c63765b5df607f","status":"passed","time":{"start":1731475967667,"stop":1731475967667,"duration":0}},{"uid":"f5df3c9f8a072182","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/f5df3c9f8a072182","status":"passed","time":{"start":1731474813200,"stop":1731474813200,"duration":0}},{"uid":"7857984e9e60a3e2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/7857984e9e60a3e2","status":"passed","time":{"start":1730875812830,"stop":1730875812830,"duration":0}},{"uid":"3b0d238030aeb275","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/3b0d238030aeb275","status":"passed","time":{"start":1730865941756,"stop":1730865941756,"duration":0}},{"uid":"6f55fbd3f255fdc8","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/6f55fbd3f255fdc8","status":"passed","time":{"start":1730186920500,"stop":1730186920501,"duration":1}},{"uid":"8c17ac1455a16e95","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/8c17ac1455a16e95","status":"passed","time":{"start":1730186750267,"stop":1730186750267,"duration":0}},{"uid":"2efb1a7a6ff600ae","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/2efb1a7a6ff600ae","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748686523,"stop":1729748686523,"duration":0}},{"uid":"7b360306d95da76b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/7b360306d95da76b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680165011,"stop":1729680165011,"duration":0}},{"uid":"ca17940e0acda75b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/ca17940e0acda75b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679367611,"stop":1729679367611,"duration":0}},{"uid":"73c3cfc4ad5e1412","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/73c3cfc4ad5e1412","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672199293,"stop":1729672199293,"duration":0}},{"uid":"3f29f66e448fa39d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/3f29f66e448fa39d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667684315,"stop":1729667684315,"duration":0}},{"uid":"5f0feb8681827e6e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/5f0feb8681827e6e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664173807,"stop":1729664173807,"duration":0}},{"uid":"fa87ad497c3a77d0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/fa87ad497c3a77d0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574250081,"stop":1729574250081,"duration":0}},{"uid":"302dc12aa4e8028c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/302dc12aa4e8028c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508366385,"stop":1729508366385,"duration":0}},{"uid":"bd4678e4f5cbb831","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/bd4678e4f5cbb831","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506660663,"stop":1729506660663,"duration":0}},{"uid":"f621647e6eb30b50","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/f621647e6eb30b50","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245930878,"stop":1729245930878,"duration":0}},{"uid":"8ae2bb87a0153846","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/8ae2bb87a0153846","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386493502,"stop":1728386493502,"duration":0}},{"uid":"beb192ba4cc5336b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/beb192ba4cc5336b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380139450,"stop":1728380139450,"duration":0}},{"uid":"349e049fd76bc0b0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/349e049fd76bc0b0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370093613,"stop":1728370093613,"duration":0}}]},"c4f3bc323a890a8c1c21c8ac6cff8b21":{"statistic":{"failed":5,"broken":14,"skipped":0,"passed":60,"unknown":0,"total":79},"items":[{"uid":"b7c02c0d2464fafc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/b7c02c0d2464fafc","status":"passed","time":{"start":1731476630712,"stop":1731476630712,"duration":0}},{"uid":"23350fc6ac78201e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/23350fc6ac78201e","status":"passed","time":{"start":1731475966989,"stop":1731475966990,"duration":1}},{"uid":"ccefb59871c5acd4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/ccefb59871c5acd4","status":"passed","time":{"start":1731474812252,"stop":1731474812252,"duration":0}},{"uid":"4b1f706ee16cb3d0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/4b1f706ee16cb3d0","status":"passed","time":{"start":1730875812128,"stop":1730875812128,"duration":0}},{"uid":"5e5789606de5512e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/5e5789606de5512e","status":"passed","time":{"start":1730865941128,"stop":1730865941128,"duration":0}},{"uid":"55539ec7b1937c12","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/55539ec7b1937c12","status":"passed","time":{"start":1730186919537,"stop":1730186919537,"duration":0}},{"uid":"6d10ab740843d79f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/6d10ab740843d79f","status":"passed","time":{"start":1730186749593,"stop":1730186749593,"duration":0}},{"uid":"86db317676ca417e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/86db317676ca417e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684953,"stop":1729748684953,"duration":0}},{"uid":"f6adc8fc2afcccdc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/f6adc8fc2afcccdc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163445,"stop":1729680163445,"duration":0}},{"uid":"38954a95e327c011","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/38954a95e327c011","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365945,"stop":1729679365945,"duration":0}},{"uid":"480d58ed31b22794","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/480d58ed31b22794","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197698,"stop":1729672197698,"duration":0}},{"uid":"d77e6a0377354201","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/d77e6a0377354201","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682732,"stop":1729667682732,"duration":0}},{"uid":"b243030c21fc3150","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/b243030c21fc3150","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172123,"stop":1729664172123,"duration":0}},{"uid":"24e6f945c701a9b1","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/24e6f945c701a9b1","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248499,"stop":1729574248499,"duration":0}},{"uid":"30e98bdb8dca5102","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/30e98bdb8dca5102","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364757,"stop":1729508364757,"duration":0}},{"uid":"c3321d21696d1e7e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/c3321d21696d1e7e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659036,"stop":1729506659036,"duration":0}},{"uid":"825de993da89de5b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/825de993da89de5b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245929203,"stop":1729245929203,"duration":0}},{"uid":"8508da982426a88d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/8508da982426a88d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491965,"stop":1728386491965,"duration":0}},{"uid":"cdb357d8801d2ea9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/cdb357d8801d2ea9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137863,"stop":1728380137863,"duration":0}},{"uid":"958962b3b5faf0ca","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/958962b3b5faf0ca","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092057,"stop":1728370092057,"duration":0}}]},"facd427b63b92a7b83f4ac87ab0c7af0":{"statistic":{"failed":8,"broken":14,"skipped":0,"passed":57,"unknown":0,"total":79},"items":[{"uid":"e037b50362598e0e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/e037b50362598e0e","status":"passed","time":{"start":1731476630894,"stop":1731476630894,"duration":0}},{"uid":"5500b101db21e0a9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/5500b101db21e0a9","status":"passed","time":{"start":1731475967111,"stop":1731475967111,"duration":0}},{"uid":"3cd0e2cfb5d161fc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/3cd0e2cfb5d161fc","status":"passed","time":{"start":1731474812424,"stop":1731474812424,"duration":0}},{"uid":"f1e8372de68de1e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/f1e8372de68de1e","status":"passed","time":{"start":1730875812249,"stop":1730875812249,"duration":0}},{"uid":"15ad7a241b8c45fb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/15ad7a241b8c45fb","status":"passed","time":{"start":1730865941244,"stop":1730865941244,"duration":0}},{"uid":"9941ef0d940e5da9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/9941ef0d940e5da9","status":"passed","time":{"start":1730186919719,"stop":1730186919719,"duration":0}},{"uid":"3746fef4c85a2893","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/3746fef4c85a2893","status":"passed","time":{"start":1730186749714,"stop":1730186749714,"duration":0}},{"uid":"4307f4b804d84abc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/4307f4b804d84abc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685522,"stop":1729748685522,"duration":0}},{"uid":"300904cade9664cc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/300904cade9664cc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163915,"stop":1729680163915,"duration":0}},{"uid":"70aa48f7c7250936","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/70aa48f7c7250936","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679366571,"stop":1729679366571,"duration":0}},{"uid":"60b701192594ec64","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/60b701192594ec64","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198286,"stop":1729672198286,"duration":0}},{"uid":"1c728dcb493eae7b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/1c728dcb493eae7b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683356,"stop":1729667683356,"duration":0}},{"uid":"6bf13a1345986c94","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/6bf13a1345986c94","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172774,"stop":1729664172774,"duration":0}},{"uid":"411e57347e9f42f0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/411e57347e9f42f0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249072,"stop":1729574249072,"duration":0}},{"uid":"d6d534042296f8b6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/d6d534042296f8b6","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365371,"stop":1729508365371,"duration":0}},{"uid":"20311a526620f28a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/20311a526620f28a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659642,"stop":1729506659642,"duration":0}},{"uid":"31b9d4695687a74e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/31b9d4695687a74e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245929828,"stop":1729245929828,"duration":0}},{"uid":"63c48d9abe66e489","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/63c48d9abe66e489","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492448,"stop":1728386492448,"duration":0}},{"uid":"d791e3f83d56f0eb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/d791e3f83d56f0eb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138451,"stop":1728380138451,"duration":0}},{"uid":"e1b1cac2bc9fe369","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/e1b1cac2bc9fe369","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092624,"stop":1728370092624,"duration":0}}]},"4614fbf5d189d669b2a9afbe419c31b6":{"statistic":{"failed":5,"broken":14,"skipped":0,"passed":60,"unknown":0,"total":79},"items":[{"uid":"890bea1add652050","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/890bea1add652050","status":"passed","time":{"start":1731476631262,"stop":1731476631493,"duration":231}},{"uid":"19cb2021fe481d6b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/19cb2021fe481d6b","status":"passed","time":{"start":1731475967354,"stop":1731475967537,"duration":183}},{"uid":"4c1175a4359d9ad7","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/4c1175a4359d9ad7","status":"passed","time":{"start":1731474812775,"stop":1731474813015,"duration":240}},{"uid":"38e49e0de144fc95","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/38e49e0de144fc95","status":"passed","time":{"start":1730875812497,"stop":1730875812701,"duration":204}},{"uid":"4adae8ed44b043b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/4adae8ed44b043b","status":"passed","time":{"start":1730865941482,"stop":1730865941627,"duration":145}},{"uid":"90bb1e4500d54afe","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/90bb1e4500d54afe","status":"passed","time":{"start":1730186920087,"stop":1730186920309,"duration":222}},{"uid":"399ecc55b1184b5b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/399ecc55b1184b5b","status":"passed","time":{"start":1730186749953,"stop":1730186750139,"duration":186}},{"uid":"2c32cce38fd5f7e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/2c32cce38fd5f7e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685956,"stop":1729748686308,"duration":352}},{"uid":"9a9ebec95c734629","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/9a9ebec95c734629","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680164352,"stop":1729680164777,"duration":425}},{"uid":"5abf739cce896764","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/5abf739cce896764","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679367007,"stop":1729679367392,"duration":385}},{"uid":"1a6af03138aa2122","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/1a6af03138aa2122","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198712,"stop":1729672199079,"duration":367}},{"uid":"b5d00861c2f6e3f3","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/b5d00861c2f6e3f3","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683815,"stop":1729667684088,"duration":273}},{"uid":"f436f39241964f12","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/f436f39241964f12","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664173202,"stop":1729664173594,"duration":392}},{"uid":"67f1da969aafec91","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/67f1da969aafec91","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249499,"stop":1729574249869,"duration":370}},{"uid":"185b43c6bf2e45cd","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/185b43c6bf2e45cd","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365815,"stop":1729508366164,"duration":349}},{"uid":"1057159e0d961cdb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/1057159e0d961cdb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506660062,"stop":1729506660458,"duration":396}},{"uid":"dce0fce1d596029b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/dce0fce1d596029b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245930254,"stop":1729245930666,"duration":412}},{"uid":"1e30f4a4c9b5669b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/1e30f4a4c9b5669b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492891,"stop":1728386493282,"duration":391}},{"uid":"55de8ffc2fe94a03","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/55de8ffc2fe94a03","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138880,"stop":1728380139236,"duration":356}},{"uid":"fdd28c04129f70aa","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/fdd28c04129f70aa","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/templates (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370093049,"stop":1728370093400,"duration":351}}]},"b479afaeccaeb0b2b306544ea95f6f33":{"statistic":{"failed":44,"broken":15,"skipped":0,"passed":20,"unknown":0,"total":79},"items":[{"uid":"b23a631b4d8d8b14","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/b23a631b4d8d8b14","status":"passed","time":{"start":1731476630236,"stop":1731476630524,"duration":288}},{"uid":"7929747185f7d57b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/7929747185f7d57b","status":"passed","time":{"start":1731475966618,"stop":1731475966866,"duration":248}},{"uid":"a95c91e82164e86a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/a95c91e82164e86a","status":"passed","time":{"start":1731474811814,"stop":1731474812077,"duration":263}},{"uid":"7bc1c8ce4ce5b2f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/7bc1c8ce4ce5b2f","status":"failed","statusDetails":"AssertionError: No successful 'voteEvent' log found | Failed Logs: None","time":{"start":1730875811778,"stop":1730875811997,"duration":219}},{"uid":"833cc018b8e7564d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/833cc018b8e7564d","status":"failed","statusDetails":"AssertionError: No successful 'voteEvent' log found | Failed Logs: None","time":{"start":1730865940777,"stop":1730865941001,"duration":224}},{"uid":"a7287c4636a0e659","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/a7287c4636a0e659","status":"failed","statusDetails":"AssertionError: No successful 'voteEvent' log found | Failed Logs: None","time":{"start":1730186919036,"stop":1730186919348,"duration":312}},{"uid":"a51cc243e512cc72","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/a51cc243e512cc72","status":"failed","statusDetails":"AssertionError: No successful 'voteEvent' log found | Failed Logs: None","time":{"start":1730186749145,"stop":1730186749464,"duration":319}},{"uid":"a96b8f18f1ab4b0f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/a96b8f18f1ab4b0f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684846,"stop":1729748684846,"duration":0}},{"uid":"e58ff50f613d1614","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/e58ff50f613d1614","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163334,"stop":1729680163334,"duration":0}},{"uid":"e302293c377d8b88","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/e302293c377d8b88","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365837,"stop":1729679365837,"duration":0}},{"uid":"3881e1e22b89c3ce","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/3881e1e22b89c3ce","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197592,"stop":1729672197592,"duration":0}},{"uid":"d3765a1a1fa028f0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/d3765a1a1fa028f0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682618,"stop":1729667682618,"duration":0}},{"uid":"be3b304aa1d99a23","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/be3b304aa1d99a23","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172015,"stop":1729664172015,"duration":0}},{"uid":"8199cc44a06d7a4e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/8199cc44a06d7a4e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248369,"stop":1729574248369,"duration":0}},{"uid":"b92dbd4b8c07e974","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/b92dbd4b8c07e974","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364648,"stop":1729508364648,"duration":0}},{"uid":"8ee8b5f6dd4d3f5e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/8ee8b5f6dd4d3f5e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506658931,"stop":1729506658931,"duration":0}},{"uid":"bce4deedc5ced6af","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/bce4deedc5ced6af","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245929097,"stop":1729245929097,"duration":0}},{"uid":"fad0291fe04cfe84","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/fad0291fe04cfe84","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491859,"stop":1728386491859,"duration":0}},{"uid":"e1ef0b18c0bb154e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/e1ef0b18c0bb154e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137757,"stop":1728380137757,"duration":0}},{"uid":"42b2cfc7dbdd365a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/42b2cfc7dbdd365a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091951,"stop":1728370091951,"duration":0}}]},"d79a2535db45bda6b7c50f297d55cad0":{"statistic":{"failed":8,"broken":15,"skipped":0,"passed":56,"unknown":0,"total":79},"items":[{"uid":"cfc7e5c1026209d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/cfc7e5c1026209d","status":"passed","time":{"start":1731476631494,"stop":1731476631494,"duration":0}},{"uid":"ca5e7a836bbe9390","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/ca5e7a836bbe9390","status":"passed","time":{"start":1731475967538,"stop":1731475967538,"duration":0}},{"uid":"1ae7335361ac3c20","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/1ae7335361ac3c20","status":"passed","time":{"start":1731474813016,"stop":1731474813017,"duration":1}},{"uid":"532c062fb48d631d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/532c062fb48d631d","status":"passed","time":{"start":1730875812702,"stop":1730875812702,"duration":0}},{"uid":"c6e3ecf7a86f4f21","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/c6e3ecf7a86f4f21","status":"passed","time":{"start":1730865941628,"stop":1730865941628,"duration":0}},{"uid":"afbedabeb6610913","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/afbedabeb6610913","status":"passed","time":{"start":1730186920311,"stop":1730186920311,"duration":0}},{"uid":"77e08e3a7b1780dd","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/77e08e3a7b1780dd","status":"passed","time":{"start":1730186750141,"stop":1730186750141,"duration":0}},{"uid":"dc10f81307c0673","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/dc10f81307c0673","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748686414,"stop":1729748686414,"duration":0}},{"uid":"df42c2ba6c0e83bb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/df42c2ba6c0e83bb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680164901,"stop":1729680164901,"duration":0}},{"uid":"d6b4b42ab1e4a06a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/d6b4b42ab1e4a06a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679367500,"stop":1729679367500,"duration":0}},{"uid":"f3d6d0cd0f9f2826","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/f3d6d0cd0f9f2826","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672199183,"stop":1729672199183,"duration":0}},{"uid":"cdb2a3a870e5d892","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/cdb2a3a870e5d892","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667684199,"stop":1729667684199,"duration":0}},{"uid":"4ae8a2d6d058896b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/4ae8a2d6d058896b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664173699,"stop":1729664173699,"duration":0}},{"uid":"a7000fe4d76c8c0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/a7000fe4d76c8c0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249973,"stop":1729574249973,"duration":0}},{"uid":"5ae337a3232f944","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/5ae337a3232f944","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508366273,"stop":1729508366273,"duration":0}},{"uid":"d79367483363cf7f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/d79367483363cf7f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506660558,"stop":1729506660558,"duration":0}},{"uid":"390454ea9bd2b60d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/390454ea9bd2b60d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245930770,"stop":1729245930770,"duration":0}},{"uid":"9cc57d2f6295fd36","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/9cc57d2f6295fd36","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386493390,"stop":1728386493390,"duration":0}},{"uid":"bd13b890f684532d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/bd13b890f684532d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380139342,"stop":1728380139342,"duration":0}},{"uid":"5c9c08cf368179ac","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/5c9c08cf368179ac","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370093504,"stop":1728370093504,"duration":0}}]},"3e0654fc84f60fdcfbe40b395f79c630":{"statistic":{"failed":8,"broken":15,"skipped":0,"passed":56,"unknown":0,"total":79},"items":[{"uid":"8dc0d2d4db174c6e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/8dc0d2d4db174c6e","status":"passed","time":{"start":1731476631077,"stop":1731476631261,"duration":184}},{"uid":"b9426a0fe0622959","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/b9426a0fe0622959","status":"passed","time":{"start":1731475967230,"stop":1731475967352,"duration":122}},{"uid":"d2a22bc794195437","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/d2a22bc794195437","status":"passed","time":{"start":1731474812596,"stop":1731474812774,"duration":178}},{"uid":"212487ad06808ded","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/212487ad06808ded","status":"passed","time":{"start":1730875812370,"stop":1730875812495,"duration":125}},{"uid":"28b9940ddad5b287","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/28b9940ddad5b287","status":"passed","time":{"start":1730865941361,"stop":1730865941480,"duration":119}},{"uid":"7b582e70ce11b5af","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/7b582e70ce11b5af","status":"passed","time":{"start":1730186919901,"stop":1730186920085,"duration":184}},{"uid":"646cb2b8f755006a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/646cb2b8f755006a","status":"passed","time":{"start":1730186749832,"stop":1730186749952,"duration":120}},{"uid":"7d700bca7f59e78a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/7d700bca7f59e78a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685847,"stop":1729748685847,"duration":0}},{"uid":"9f24ca6670d0fb3e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/9f24ca6670d0fb3e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680164243,"stop":1729680164243,"duration":0}},{"uid":"ba22627ebbd8f334","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/ba22627ebbd8f334","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679366899,"stop":1729679366899,"duration":0}},{"uid":"2c67cf059ff4b2d2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/2c67cf059ff4b2d2","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198605,"stop":1729672198605,"duration":0}},{"uid":"bc444e75b0c0b050","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/bc444e75b0c0b050","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683697,"stop":1729667683697,"duration":0}},{"uid":"5cee5c08c3a99b42","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/5cee5c08c3a99b42","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664173095,"stop":1729664173095,"duration":0}},{"uid":"69ecf8806cef83c2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/69ecf8806cef83c2","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249392,"stop":1729574249392,"duration":0}},{"uid":"889aca47da17d069","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/889aca47da17d069","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365704,"stop":1729508365704,"duration":0}},{"uid":"d504fc1235420507","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/d504fc1235420507","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659955,"stop":1729506659955,"duration":0}},{"uid":"122009a8491c41c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/122009a8491c41c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245930148,"stop":1729245930148,"duration":0}},{"uid":"63bd765dbcec7c8e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/63bd765dbcec7c8e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492781,"stop":1728386492781,"duration":0}},{"uid":"84aab5227cf5eed9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/84aab5227cf5eed9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138774,"stop":1728380138774,"duration":0}},{"uid":"7b41d60e061f9540","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/7b41d60e061f9540","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092942,"stop":1728370092942,"duration":0}}]},"06580cb02b339767857019902ae34541":{"statistic":{"failed":8,"broken":15,"skipped":0,"passed":56,"unknown":0,"total":79},"items":[{"uid":"10215b8312d14a42","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/10215b8312d14a42","status":"passed","time":{"start":1731476098074,"stop":1731476098332,"duration":258}},{"uid":"371c92ade94db083","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/371c92ade94db083","status":"passed","time":{"start":1731475435569,"stop":1731475435756,"duration":187}},{"uid":"dd2caaf9d4607c2d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/dd2caaf9d4607c2d","status":"passed","time":{"start":1731474279230,"stop":1731474279466,"duration":236}},{"uid":"7006616cec13675a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/7006616cec13675a","status":"passed","time":{"start":1730875326410,"stop":1730875326802,"duration":392}},{"uid":"d4faa9f96a3be34b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/d4faa9f96a3be34b","status":"passed","time":{"start":1730865456109,"stop":1730865456301,"duration":192}},{"uid":"6701fdd033a8498d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/6701fdd033a8498d","status":"passed","time":{"start":1730186433111,"stop":1730186433363,"duration":252}},{"uid":"f3b76286b2c0382","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/f3b76286b2c0382","status":"passed","time":{"start":1730186263842,"stop":1730186264020,"duration":178}},{"uid":"f54e2b0267f892dc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/f54e2b0267f892dc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684046,"stop":1729748684046,"duration":0}},{"uid":"ba7a0869327e9fe4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/ba7a0869327e9fe4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680162422,"stop":1729680162422,"duration":0}},{"uid":"d067638b0c1c1cd3","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/d067638b0c1c1cd3","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679364892,"stop":1729679364892,"duration":0}},{"uid":"e31fc3871a8ac957","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/e31fc3871a8ac957","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672196683,"stop":1729672196683,"duration":0}},{"uid":"2c43b3ed3755ab36","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/2c43b3ed3755ab36","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667681718,"stop":1729667681718,"duration":0}},{"uid":"85b1a33927f01e4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/85b1a33927f01e4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664171146,"stop":1729664171146,"duration":0}},{"uid":"e4b2f67bcd52cb30","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/e4b2f67bcd52cb30","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574247330,"stop":1729574247330,"duration":0}},{"uid":"7d9fae028e77e9f7","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/7d9fae028e77e9f7","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508363725,"stop":1729508363725,"duration":0}},{"uid":"f308191a2ccfaec8","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/f308191a2ccfaec8","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506657994,"stop":1729506657994,"duration":0}},{"uid":"70b46691ce18e556","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/70b46691ce18e556","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245928141,"stop":1729245928141,"duration":0}},{"uid":"86eb8548b3972d08","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/86eb8548b3972d08","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491033,"stop":1728386491033,"duration":0}},{"uid":"ea5efc8fff0b8c0d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/ea5efc8fff0b8c0d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380136839,"stop":1728380136839,"duration":0}},{"uid":"a8374f0b38aeaf99","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/a8374f0b38aeaf99","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091053,"stop":1728370091053,"duration":0}}]},"f3a838b08baad92152078eb3339eeab2":{"statistic":{"failed":6,"broken":14,"skipped":0,"passed":59,"unknown":0,"total":79},"items":[{"uid":"60814c0550dd05a6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/60814c0550dd05a6","status":"passed","time":{"start":1731476630895,"stop":1731476631074,"duration":179}},{"uid":"c86abc137efe56ad","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/c86abc137efe56ad","status":"passed","time":{"start":1731475967112,"stop":1731475967228,"duration":116}},{"uid":"7a0b2cb858a363ef","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/7a0b2cb858a363ef","status":"passed","time":{"start":1731474812425,"stop":1731474812594,"duration":169}},{"uid":"224fcca1b3ff828a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/224fcca1b3ff828a","status":"passed","time":{"start":1730875812250,"stop":1730875812368,"duration":118}},{"uid":"f0b230914d608d66","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/f0b230914d608d66","status":"passed","time":{"start":1730865941245,"stop":1730865941359,"duration":114}},{"uid":"9bb023265a86b04","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/9bb023265a86b04","status":"passed","time":{"start":1730186919720,"stop":1730186919898,"duration":178}},{"uid":"492adf766a435f07","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/492adf766a435f07","status":"passed","time":{"start":1730186749715,"stop":1730186749829,"duration":114}},{"uid":"bf8d9977165a238d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/bf8d9977165a238d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685629,"stop":1729748685629,"duration":0}},{"uid":"3967365d87f696ac","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/3967365d87f696ac","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680164024,"stop":1729680164024,"duration":0}},{"uid":"ad075b6afc706706","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/ad075b6afc706706","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679366681,"stop":1729679366681,"duration":0}},{"uid":"55588a89d36eca4f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/55588a89d36eca4f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198391,"stop":1729672198391,"duration":0}},{"uid":"2abe4f88f1aa4c99","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/2abe4f88f1aa4c99","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683468,"stop":1729667683468,"duration":0}},{"uid":"6f99b6f5d82724b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/6f99b6f5d82724b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172880,"stop":1729664172880,"duration":0}},{"uid":"c84559b89d15dea9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/c84559b89d15dea9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249178,"stop":1729574249178,"duration":0}},{"uid":"3900cff902e2bbd0","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/3900cff902e2bbd0","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365480,"stop":1729508365480,"duration":0}},{"uid":"c0da303d03a8dd21","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/c0da303d03a8dd21","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659746,"stop":1729506659746,"duration":0}},{"uid":"a1dc545569c3998e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/a1dc545569c3998e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245929934,"stop":1729245929934,"duration":0}},{"uid":"b2def9ad092eb278","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/b2def9ad092eb278","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492557,"stop":1728386492557,"duration":0}},{"uid":"b7f1d15810def0da","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/b7f1d15810def0da","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138559,"stop":1728380138559,"duration":0}},{"uid":"dbc00ae38121cf29","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/dbc00ae38121cf29","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092730,"stop":1728370092730,"duration":0}}]},"e60a8efb6389f125260a50658880d0d3":{"statistic":{"failed":8,"broken":14,"skipped":0,"passed":57,"unknown":0,"total":79},"items":[{"uid":"3cb498dfe7346b5","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/3cb498dfe7346b5","status":"passed","time":{"start":1731476631076,"stop":1731476631076,"duration":0}},{"uid":"ed377b056604b9ed","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/ed377b056604b9ed","status":"passed","time":{"start":1731475967229,"stop":1731475967229,"duration":0}},{"uid":"47728d52280e3580","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/47728d52280e3580","status":"passed","time":{"start":1731474812595,"stop":1731474812595,"duration":0}},{"uid":"27aa698c520308f6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/27aa698c520308f6","status":"passed","time":{"start":1730875812369,"stop":1730875812369,"duration":0}},{"uid":"af3e5cb45669d5db","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/af3e5cb45669d5db","status":"passed","time":{"start":1730865941360,"stop":1730865941360,"duration":0}},{"uid":"db7fb4f396c39d0c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/db7fb4f396c39d0c","status":"passed","time":{"start":1730186919900,"stop":1730186919900,"duration":0}},{"uid":"794984deeea96ffe","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/794984deeea96ffe","status":"passed","time":{"start":1730186749831,"stop":1730186749831,"duration":0}},{"uid":"ba4fdcf0d4dffe52","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/ba4fdcf0d4dffe52","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685737,"stop":1729748685737,"duration":0}},{"uid":"59ab417032c55534","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/59ab417032c55534","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680164132,"stop":1729680164132,"duration":0}},{"uid":"e712d149ed5f7fb4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/e712d149ed5f7fb4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679366789,"stop":1729679366789,"duration":0}},{"uid":"d23808e2b88f2956","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/d23808e2b88f2956","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198496,"stop":1729672198496,"duration":0}},{"uid":"7c45c9cb8db5fa58","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/7c45c9cb8db5fa58","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683581,"stop":1729667683581,"duration":0}},{"uid":"40a19a356015672d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/40a19a356015672d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172986,"stop":1729664172986,"duration":0}},{"uid":"594ae447e17d3793","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/594ae447e17d3793","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574249284,"stop":1729574249284,"duration":0}},{"uid":"52872b7e07513c34","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/52872b7e07513c34","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365590,"stop":1729508365590,"duration":0}},{"uid":"35471da0bb11200e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/35471da0bb11200e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659849,"stop":1729506659849,"duration":0}},{"uid":"21bd374d981df65c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/21bd374d981df65c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245930040,"stop":1729245930040,"duration":0}},{"uid":"e511c290c6c035f6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/e511c290c6c035f6","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492667,"stop":1728386492667,"duration":0}},{"uid":"4a66709f0dcbc347","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/4a66709f0dcbc347","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138666,"stop":1728380138666,"duration":0}},{"uid":"9d6635acdf74204f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/9d6635acdf74204f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092835,"stop":1728370092835,"duration":0}}]},"398b8ccba1d43478bb443a9fb65225bb":{"statistic":{"failed":14,"broken":15,"skipped":0,"passed":50,"unknown":0,"total":79},"items":[{"uid":"20cf8d3e9d915547","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/20cf8d3e9d915547","status":"passed","time":{"start":1731476098610,"stop":1731476098610,"duration":0}},{"uid":"6f1b46e53a40115b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/6f1b46e53a40115b","status":"passed","time":{"start":1731475435960,"stop":1731475435960,"duration":0}},{"uid":"c6dedf0f81bad13d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/c6dedf0f81bad13d","status":"passed","time":{"start":1731474279716,"stop":1731474279717,"duration":1}},{"uid":"dcd068bbbafd3b1e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/dcd068bbbafd3b1e","status":"passed","time":{"start":1730875326990,"stop":1730875326990,"duration":0}},{"uid":"1a431f5c44acf1ba","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/1a431f5c44acf1ba","status":"passed","time":{"start":1730865456490,"stop":1730865456491,"duration":1}},{"uid":"2ade07affb782828","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/2ade07affb782828","status":"passed","time":{"start":1730186433629,"stop":1730186433629,"duration":0}},{"uid":"3760c84cdfbc76e1","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/3760c84cdfbc76e1","status":"passed","time":{"start":1730186264210,"stop":1730186264210,"duration":0}},{"uid":"afd6498c91e7e235","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/afd6498c91e7e235","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684400,"stop":1729748684400,"duration":0}},{"uid":"a041f1a015f44996","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/a041f1a015f44996","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680162898,"stop":1729680162898,"duration":0}},{"uid":"1a1a51a59af2c3f4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/1a1a51a59af2c3f4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365399,"stop":1729679365399,"duration":0}},{"uid":"abbc699739c73d78","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/abbc699739c73d78","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197166,"stop":1729672197166,"duration":0}},{"uid":"4aae5fffb8a2d325","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/4aae5fffb8a2d325","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682158,"stop":1729667682158,"duration":0}},{"uid":"fb26be359cd791ca","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/fb26be359cd791ca","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664171573,"stop":1729664171573,"duration":0}},{"uid":"2dfcf8c2ad5cc588","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/2dfcf8c2ad5cc588","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574247921,"stop":1729574247921,"duration":0}},{"uid":"eb67b358ed85c0dc","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/eb67b358ed85c0dc","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364195,"stop":1729508364195,"duration":0}},{"uid":"66ae881999b00b48","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/66ae881999b00b48","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506658509,"stop":1729506658509,"duration":0}},{"uid":"f7f57f258b4be66e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/f7f57f258b4be66e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245928669,"stop":1729245928669,"duration":0}},{"uid":"91688211b4e945bb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/91688211b4e945bb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491431,"stop":1728386491431,"duration":0}},{"uid":"4003620a57371e41","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/4003620a57371e41","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137330,"stop":1728380137330,"duration":0}},{"uid":"dcb94c9dae725cfe","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/dcb94c9dae725cfe","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091524,"stop":1728370091524,"duration":0}}]},"bf5102b0fa26be747eb8ee000c1d24e7":{"statistic":{"failed":15,"broken":15,"skipped":0,"passed":49,"unknown":0,"total":79},"items":[{"uid":"f92b654acf3c7377","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/f92b654acf3c7377","status":"passed","time":{"start":1731476629299,"stop":1731476629299,"duration":0}},{"uid":"9ecc9721d2555b33","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/9ecc9721d2555b33","status":"passed","time":{"start":1731475965892,"stop":1731475965892,"duration":0}},{"uid":"a020c08fd50dc269","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/a020c08fd50dc269","status":"passed","time":{"start":1731474810917,"stop":1731474810918,"duration":1}},{"uid":"5b39323a4a33dfe3","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/5b39323a4a33dfe3","status":"passed","time":{"start":1730875811284,"stop":1730875811284,"duration":0}},{"uid":"64779f49c67695ee","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/64779f49c67695ee","status":"passed","time":{"start":1730865940263,"stop":1730865940264,"duration":1}},{"uid":"9f1a93700258cdb5","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/9f1a93700258cdb5","status":"passed","time":{"start":1730186918378,"stop":1730186918379,"duration":1}},{"uid":"fc0a963c552368d6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/fc0a963c552368d6","status":"passed","time":{"start":1730186748527,"stop":1730186748527,"duration":0}},{"uid":"565c573eeed1ee1e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/565c573eeed1ee1e","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748684509,"stop":1729748684509,"duration":0}},{"uid":"299db80cec56b429","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/299db80cec56b429","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163006,"stop":1729680163006,"duration":0}},{"uid":"83e8c4498223241b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/83e8c4498223241b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679365508,"stop":1729679365508,"duration":0}},{"uid":"1869d9e8c3325bc8","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/1869d9e8c3325bc8","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672197274,"stop":1729672197274,"duration":0}},{"uid":"96e4ce9af3555ce9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/96e4ce9af3555ce9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667682271,"stop":1729667682271,"duration":0}},{"uid":"b3cff367bfb23c07","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/b3cff367bfb23c07","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664171681,"stop":1729664171681,"duration":0}},{"uid":"670a5c6262b89a4b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/670a5c6262b89a4b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248030,"stop":1729574248030,"duration":0}},{"uid":"7fb47cdaef583553","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/7fb47cdaef583553","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508364307,"stop":1729508364307,"duration":0}},{"uid":"71bf404371f81928","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/71bf404371f81928","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506658615,"stop":1729506658615,"duration":0}},{"uid":"27dc2f65bd9404c4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/27dc2f65bd9404c4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245928776,"stop":1729245928776,"duration":0}},{"uid":"683580d6e2d7989d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/683580d6e2d7989d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386491538,"stop":1728386491538,"duration":0}},{"uid":"21bf4d1f8e949d9a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/21bf4d1f8e949d9a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380137437,"stop":1728380137437,"duration":0}},{"uid":"c2c5a81628eb1773","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/c2c5a81628eb1773","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370091631,"stop":1728370091631,"duration":0}}]},"8f66ed3039064d88cfc2340a1bec5701":{"statistic":{"failed":5,"broken":15,"skipped":0,"passed":59,"unknown":0,"total":79},"items":[{"uid":"28c377c454aae55a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/28c377c454aae55a","status":"passed","time":{"start":1731476630714,"stop":1731476630893,"duration":179}},{"uid":"b2a064a5f9aaaea2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/b2a064a5f9aaaea2","status":"passed","time":{"start":1731475966991,"stop":1731475967109,"duration":118}},{"uid":"c13ff42d5dada289","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/c13ff42d5dada289","status":"passed","time":{"start":1731474812253,"stop":1731474812422,"duration":169}},{"uid":"81d3a1f829a0345","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/81d3a1f829a0345","status":"passed","time":{"start":1730875812129,"stop":1730875812248,"duration":119}},{"uid":"54cc59d1e1478ace","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/54cc59d1e1478ace","status":"passed","time":{"start":1730865941129,"stop":1730865941243,"duration":114}},{"uid":"a86ad0b73e37d65e","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/a86ad0b73e37d65e","status":"passed","time":{"start":1730186919539,"stop":1730186919717,"duration":178}},{"uid":"99aa4b4b3708fbe6","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/99aa4b4b3708fbe6","status":"passed","time":{"start":1730186749594,"stop":1730186749712,"duration":118}},{"uid":"eb618623a78c0851","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/eb618623a78c0851","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748685413,"stop":1729748685413,"duration":0}},{"uid":"e09676ec1bdb6264","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/e09676ec1bdb6264","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680163805,"stop":1729680163805,"duration":0}},{"uid":"3c6245f81124c3f2","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/3c6245f81124c3f2","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679366461,"stop":1729679366461,"duration":0}},{"uid":"c96918d791057a0a","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/c96918d791057a0a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672198178,"stop":1729672198178,"duration":0}},{"uid":"16e7e8d019628f7d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/16e7e8d019628f7d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667683241,"stop":1729667683241,"duration":0}},{"uid":"8eb91cb99b7d72de","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/8eb91cb99b7d72de","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664172667,"stop":1729664172667,"duration":0}},{"uid":"a8f31b4de2649a4f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/a8f31b4de2649a4f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574248965,"stop":1729574248965,"duration":0}},{"uid":"3c1930ac575303fd","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/3c1930ac575303fd","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508365259,"stop":1729508365259,"duration":0}},{"uid":"c4f580030e89c9e9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/c4f580030e89c9e9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506659536,"stop":1729506659536,"duration":0}},{"uid":"5d23e2408e211d10","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/5d23e2408e211d10","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245929721,"stop":1729245929721,"duration":0}},{"uid":"8df377773b2d1c9","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/8df377773b2d1c9","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386492340,"stop":1728386492340,"duration":0}},{"uid":"2b37594fc46ad332","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/2b37594fc46ad332","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380138343,"stop":1728380138343,"duration":0}},{"uid":"4d5df67ce3a47bd4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/4d5df67ce3a47bd4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/auth/login (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370092517,"stop":1728370092517,"duration":0}}]},"765acc991ec56447f966e3885e76d93c":{"statistic":{"failed":5,"broken":13,"skipped":0,"passed":61,"unknown":0,"total":79},"items":[{"uid":"e49f7b874fbc768b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/e49f7b874fbc768b","status":"passed","time":{"start":1731476094870,"stop":1731476097279,"duration":2409}},{"uid":"d46cf883d496dc3f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/d46cf883d496dc3f","status":"passed","time":{"start":1731475432869,"stop":1731475435056,"duration":2187}},{"uid":"69ab9af739b911e5","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/69ab9af739b911e5","status":"passed","time":{"start":1731474275951,"stop":1731474278489,"duration":2538}},{"uid":"5ba3d2b6350a749d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/75//#testresult/5ba3d2b6350a749d","status":"passed","time":{"start":1730875323479,"stop":1730875325860,"duration":2381}},{"uid":"73bb2f81225d0e58","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/74//#testresult/73bb2f81225d0e58","status":"passed","time":{"start":1730865453287,"stop":1730865455578,"duration":2291}},{"uid":"a846b185d14858ba","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/73//#testresult/a846b185d14858ba","status":"passed","time":{"start":1730186429388,"stop":1730186432321,"duration":2933}},{"uid":"9a2af789451c007","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/72//#testresult/9a2af789451c007","status":"passed","time":{"start":1730186260565,"stop":1730186263333,"duration":2768}},{"uid":"41dff6c595e37676","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/71//#testresult/41dff6c595e37676","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729748683559,"stop":1729748683911,"duration":352}},{"uid":"35d39e250bd0f32d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/70//#testresult/35d39e250bd0f32d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729680161918,"stop":1729680162288,"duration":370}},{"uid":"4b143b3813c8b4ac","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/69//#testresult/4b143b3813c8b4ac","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729679364192,"stop":1729679364756,"duration":564}},{"uid":"6d3586712159617c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/68//#testresult/6d3586712159617c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729672196083,"stop":1729672196551,"duration":468}},{"uid":"7faca3b69b785cb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/67//#testresult/7faca3b69b785cb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729667681139,"stop":1729667681579,"duration":440}},{"uid":"87b7849fe55d282b","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/66//#testresult/87b7849fe55d282b","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729664170573,"stop":1729664171013,"duration":440}},{"uid":"c12647eddb1fba2c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/65//#testresult/c12647eddb1fba2c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729574246822,"stop":1729574247196,"duration":374}},{"uid":"bb9ed2c0a2d6cacb","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/64//#testresult/bb9ed2c0a2d6cacb","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729508363235,"stop":1729508363588,"duration":353}},{"uid":"5eacbbdac14f1a4","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/63//#testresult/5eacbbdac14f1a4","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729506657505,"stop":1729506657861,"duration":356}},{"uid":"689ce9ef79c9b702","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/62//#testresult/689ce9ef79c9b702","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1729245927735,"stop":1729245928007,"duration":272}},{"uid":"a757f7262a70c85f","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/61//#testresult/a757f7262a70c85f","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728386490463,"stop":1728386490899,"duration":436}},{"uid":"46affcb0ed2e628c","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/60//#testresult/46affcb0ed2e628c","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728380136237,"stop":1728380136705,"duration":468}},{"uid":"6c33e4b99a16045d","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/59//#testresult/6c33e4b99a16045d","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.agents.cardanoapi.io', port=443): Max retries exceeded with url: /api/agents (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.agents.cardanoapi.io'. (_ssl.c:1000)\")))","time":{"start":1728370090481,"stop":1728370090919,"duration":438}}]},"5303b14a2eb3c0648518bffc5208ab10":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":2,"unknown":0,"total":3},"items":[{"uid":"4b04eceaa7039e03","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/4b04eceaa7039e03","status":"passed","time":{"start":1731476629922,"stop":1731476630235,"duration":313}},{"uid":"ab797ed7fac84c75","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/77//#testresult/ab797ed7fac84c75","status":"passed","time":{"start":1731475966375,"stop":1731475966616,"duration":241}},{"uid":"41793f9d493b7e10","reportUrl":"https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/76//#testresult/41793f9d493b7e10","status":"failed","statusDetails":"AssertionError: No successful 'create infoAction proposal' log found | Failed Logs: None","time":{"start":1731474811480,"stop":1731474811780,"duration":300}}]}}